# Site settings
title: OrangeMoon'Blog
SEOTitle: OrangeMoon的博客 | OrangeMoon
header-img: img/my sky.png
email: truekai@foxmail.com
description: "Every failure is leading towards success."
keyword: "OrangeMoon, Orange, 橙月的博客, Spark，Hadoop，Java"
url: "http://OrangeMoonOrange.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/OrangeMoonOrange/" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "关注时空大数据技术!"
sidebar-avatar: /img/IMG_1259(20191005-012358).JPG     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    OrangeMoonOrange
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
twitter_username:   orangemoon




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: disqus_9HTn3zDtMd
# Gitalk
 gitalk:
  enable:     #是否开启Gitalk评论
  clientID: 'c0ea2c6bbb332bf9cfa3'    #生成的clientID
  clientSecret: 'ddf2b5bd1183c880b4b12ac6053eb5a05d14825f'   #同上
  repo: OrangeMoonOrange.github.io   #仓库名称
  owner: OrangeMoonOrange    #github用户名
  admin: OrangeMoonOrange


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-177358926-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "Spark",
        href: "https://spark.apache.org/"
    },{
        title: "Hadoop",
        href: "http://hadoop.apache.org/"
    }
]
